version: "3"
services:
  jenkins:
    build: .
    image: jenkins:jcasc
    container_name: "jenkins"
    ports:
      - "8080:8080"
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=zubur1
