version: "3"
services:
  jenkins:
    build: .
    image: jenkins:jcasc
    container_name: "jenkins"
    env_file:
      - .env
    networks:
      - jenkins
  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jenkins
    networks:
      - jenkins
networks:
  jenkins:
    driver: bridge
      


